services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: yadawy_app
      POSTGRES_PASSWORD: "-MLFomczgIz-Iqqwb_9gbNCL2UXEnzuy"
    volumes:
      - yadawy_app_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "Roxb5r4aNjPEpBQihoc9Q_smCcUpmFVO"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: yadawy_app_test
      POSTGRES_PASSWORD: "Jq5r7O_F79KxCpwknDqCQppb-b3c9iIV"
    volumes:
      - yadawy_app_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "2vHBGZdO9yws2OlCPy5iYiJAPCBU0Do-"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  yadawy_app_data:
  yadawy_app_test_data:
